### ISSUE TITLE
() -> Void

### ISSUE THREAD

**Issue by ochococo** [DroidsOnRoids/swift-style-guide#8]
Please consider this example:

``` swift
(() -> ()) -> ()
```

vs

``` swift
(() -> Void) -> Void
```

I find the second one more readable and much easier to scan.

**Comment by michaello** [comment]
ja: +
krzysio: +
monsun: +
sochal: +
mrozu: +/-
pawel: -
cino: -
marcel: whatever
pawel ch: +
bart: +/-

**Comment by sochalewski** [comment]
Closed. The current state is no rule, use it depending on _per project_ arragnements.
